import json
import boto3
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from datetime import datetime
import io
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)

class ProfessionalReportGenerator:
    def __init__(self):
        self.s3 = boto3.client('s3')
        self.dynamodb = boto3.resource('dynamodb')
        
    def generate_comprehensive_report(self, company_data):
        """Generate professional ESG report"""
        try:
            # Create PDF buffer
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5*inch)
            
            # Get styles
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                spaceAfter=30,
                textColor=colors.HexColor('#2c3e50'),
                alignment=1  # Center
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=16,
                spaceAfter=12,
                textColor=colors.HexColor('#87A96B'),
                borderWidth=1,
                borderColor=colors.HexColor('#87A96B'),
                borderPadding=5
            )
            
            # Build report content
            story = []
            
            # Title Page
            story.append(Paragraph("ESG INTELLIGENCE REPORT", title_style))
            story.append(Spacer(1, 20))
            
            # Company Header
            company_info = f"""
            <b>Company:</b> {company_data['company_name']}<br/>
            <b>Sector:</b> {company_data['sector']}<br/>
            <b>Country:</b> {company_data['country']}<br/>
            <b>Analysis Date:</b> {datetime.now().strftime('%B %d, %Y')}<br/>
            <b>Report Generated by:</b> ESGenius AI Platform
            """
            story.append(Paragraph(company_info, styles['Normal']))
            story.append(Spacer(1, 30))
            
            # Executive Summary
            story.append(Paragraph("EXECUTIVE SUMMARY", heading_style))
            
            executive_summary = f"""
            This comprehensive ESG analysis of {company_data['company_name']} reveals an overall 
            ESG score of <b>{company_data['esg_score']}/100</b> with a rating of <b>"{company_data['rating']}"</b>.
            
            The analysis is based on real-time data collection from multiple sources including 
            company websites, news articles, and regulatory filings. Our proprietary AI algorithms 
            have processed {len(company_data.get('news_evidence', []))} relevant news sources 
            to provide this assessment.
            
            <b>Key Findings:</b><br/>
            • Environmental Performance: {company_data['environmental']}/25<br/>
            • Social Responsibility: {company_data['social']}/25<br/>
            • Corporate Governance: {company_data['governance']}/25<br/>
            • Innovation & Technology: {company_data['innovation']}/25
            """
            story.append(Paragraph(executive_summary, styles['Normal']))
            story.append(Spacer(1, 20))
            
            # ESG Score Breakdown Table
            story.append(Paragraph("ESG PERFORMANCE BREAKDOWN", heading_style))
            
            score_data = [
                ['ESG Category', 'Score', 'Max Score', 'Performance'],
                ['Environmental', f"{company_data['environmental']}", '25', self.get_performance_level(company_data['environmental'], 25)],
                ['Social', f"{company_data['social']}", '25', self.get_performance_level(company_data['social'], 25)],
                ['Governance', f"{company_data['governance']}", '25', self.get_performance_level(company_data['governance'], 25)],
                ['Innovation', f"{company_data['innovation']}", '25', self.get_performance_level(company_data['innovation'], 25)],
                ['TOTAL SCORE', f"{company_data['esg_score']}", '100', company_data['rating']]
            ]
            
            score_table = Table(score_data, colWidths=[2*inch, 1*inch, 1*inch, 1.5*inch])
            score_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#87A96B')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -2), colors.beige),
                ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#A8C090')),
                ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(score_table)
            story.append(Spacer(1, 20))
            
            # News Evidence Section
            if company_data.get('news_evidence'):
                story.append(Paragraph("SUPPORTING EVIDENCE & NEWS ANALYSIS", heading_style))
                
                evidence_text = f"Our analysis identified {len(company_data['news_evidence'])} relevant news sources and ESG-related publications:"
                story.append(Paragraph(evidence_text, styles['Normal']))
                story.append(Spacer(1, 10))
                
                for i, news in enumerate(company_data['news_evidence'][:5], 1):
                    news_item = f"""
                    <b>{i}. {news['title']}</b><br/>
                    Source: {news['source']} | Date: {news['date']}<br/>
                    Summary: {news['snippet']}<br/>
                    Relevance Score: {news['relevance_score']}/10<br/>
                    <i>URL: {news['url']}</i>
                    """
                    story.append(Paragraph(news_item, styles['Normal']))
                    story.append(Spacer(1, 10))
            
            # Methodology Section
            story.append(Paragraph("METHODOLOGY & DATA SOURCES", heading_style))
            
            methodology = f"""
            <b>Data Collection:</b><br/>
            • Real-time web scraping of company sustainability pages<br/>
            • News article analysis from {len(company_data.get('news_evidence', []))} sources<br/>
            • Regulatory filing analysis<br/>
            • Industry benchmark comparison<br/>
            
            <b>AI Analysis:</b><br/>
            • Amazon Bedrock AI for content processing<br/>
            • Natural Language Processing for ESG content extraction<br/>
            • Machine Learning algorithms for score calculation<br/>
            • Sector-specific benchmarking<br/>
            
            <b>Quality Assurance:</b><br/>
            • Data Quality Score: {company_data.get('data_quality', {}).get('quality_score', 'N/A')}/10<br/>
            • Sources Analyzed: {company_data.get('data_quality', {}).get('data_sources', 'N/A')}<br/>
            • Confidence Level: {self.calculate_confidence_level(company_data)}%
            """
            story.append(Paragraph(methodology, styles['Normal']))
            story.append(Spacer(1, 20))
            
            # Recommendations Section
            story.append(Paragraph("RECOMMENDATIONS & NEXT STEPS", heading_style))
            
            recommendations = self.generate_recommendations(company_data)
            story.append(Paragraph(recommendations, styles['Normal']))
            story.append(Spacer(1, 20))
            
            # Footer
            footer = f"""
            <i>This report was generated by ESGenius AI Platform on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}.<br/>
            For questions or additional analysis, contact: support@esgenius.ai<br/>
            © 2025 ESGenius AI - Professional ESG Intelligence Platform</i>
            """
            story.append(Paragraph(footer, styles['Normal']))
            
            # Build PDF
            doc.build(story)
            
            # Get PDF content
            pdf_content = buffer.getvalue()
            buffer.close()
            
            return pdf_content
            
        except Exception as e:
            logger.error(f"Report generation error: {str(e)}")
            raise e
    
    def get_performance_level(self, score, max_score):
        """Get performance level based on score"""
        percentage = (score / max_score) * 100
        if percentage >= 85:
            return "Excellent"
        elif percentage >= 70:
            return "Good"
        elif percentage >= 55:
            return "Fair"
        else:
            return "Needs Improvement"
    
    def calculate_confidence_level(self, company_data):
        """Calculate confidence level based on data quality"""
        quality_score = company_data.get('data_quality', {}).get('quality_score', 5)
        max_quality = company_data.get('data_quality', {}).get('max_score', 10)
        return round((quality_score / max_quality) * 100)
    
    def generate_recommendations(self, company_data):
        """Generate specific recommendations based on ESG scores"""
        recommendations = []
        
        # Environmental recommendations
        if company_data['environmental'] < 20:
            recommendations.append("• Develop comprehensive carbon reduction strategy")
            recommendations.append("• Increase renewable energy adoption")
            recommendations.append("• Implement circular economy principles")
        
        # Social recommendations
        if company_data['social'] < 20:
            recommendations.append("• Enhance diversity and inclusion programs")
            recommendations.append("• Strengthen community engagement initiatives")
            recommendations.append("• Improve employee welfare and development")
        
        # Governance recommendations
        if company_data['governance'] < 20:
            recommendations.append("• Strengthen board independence and diversity")
            recommendations.append("• Enhance transparency in ESG reporting")
            recommendations.append("• Implement robust ethics and compliance programs")
        
        # Innovation recommendations
        if company_data['innovation'] < 20:
            recommendations.append("• Invest in sustainable technology development")
            recommendations.append("• Adopt digital ESG monitoring tools")
            recommendations.append("• Collaborate on industry sustainability initiatives")
        
        if not recommendations:
            recommendations.append("• Continue maintaining excellent ESG performance")
            recommendations.append("• Share best practices with industry peers")
            recommendations.append("• Consider setting more ambitious sustainability targets")
        
        return "<br/>".join(recommendations)

def lambda_handler(event, context):
    """Lambda handler for professional report generation"""
    try:
        generator = ProfessionalReportGenerator()
        
        # Parse request body
        if isinstance(event.get('body'), str):
            body = json.loads(event['body'])
        else:
            body = event.get('body', {})
        
        company_name = body.get('company_name', '')
        if not company_name:
            return {
                'statusCode': 400,
                'headers': {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*'
                },
                'body': json.dumps({'error': 'Company name is required'})
            }
        
        # Get company data (this would typically come from the analysis)
        # For now, we'll use the provided data or fetch from DynamoDB
        company_data = body.get('company_data', {})
        
        if not company_data:
            return {
                'statusCode': 400,
                'headers': {
                    'Content-Type': 'application/json',
                    'Access-Control-Allow-Origin': '*'
                },
                'body': json.dumps({'error': 'Company data is required for report generation'})
            }
        
        # Generate PDF report
        pdf_content = generator.generate_comprehensive_report(company_data)
        
        # Upload to S3
        s3_key = f"reports/{company_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        bucket_name = 'esgreportingstack-esgreportsbucket402cc95c-reuojjubudza'  # Your reports bucket
        
        generator.s3.put_object(
            Bucket=bucket_name,
            Key=s3_key,
            Body=pdf_content,
            ContentType='application/pdf'
        )
        
        # Generate presigned URL for download
        download_url = generator.s3.generate_presigned_url(
            'get_object',
            Params={'Bucket': bucket_name, 'Key': s3_key},
            ExpiresIn=3600  # 1 hour
        )
        
        return {
            'statusCode': 200,
            'headers': {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*'
            },
            'body': json.dumps({
                'message': 'Professional ESG report generated successfully',
                'download_url': download_url,
                'report_size': len(pdf_content),
                'generated_at': datetime.now().isoformat()
            })
        }
        
    except Exception as e:
        logger.error(f"Report generation error: {str(e)}")
        return {
            'statusCode': 500,
            'headers': {
                'Content-Type': 'application/json',
                'Access-Control-Allow-Origin': '*'
            },
            'body': json.dumps({'error': str(e)})
        }
